services:
  app:
    build: .
    container_name: 'todo-app'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/todoapp
      - JWT_SECRET='your_jwt_secret_key'
      - NODE_ENV='development'
      - PORT=5004
    ports:
      - "5004:5004"
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=todoapp'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data: